(() => {
'use strict';
const $=id=>document.getElementById(id), state={records:[],market:[],charts:{}};
const filters=[['state','State','All States','state'],['district','District / Region','All Districts / Regions','district'],['centre','Centre / Region','All Centres / Regions','centre'],['fiber','Fiber','All Fibers','fiber'],['product','Yarn Category','All Yarn Categories','product'],['yarn_type','Yarn Type','All Yarn Types','yarn_type'],['spinning','Spinning','All Spinning Types','spinning'],['count','Count','All Counts','count'],['blend','Blend','All Blends','blend'],['yarn_name','Yarn Name','All Yarn Names','yarn_name'],['year','Year','All Years','year'],['month','Month','All Months','month']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number.isFinite(Number(v))?`₹${Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—';
const unique=a=>[...new Set(a.filter(v=>v!==undefined&&v!==null&&String(v)!==''))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true}));
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
function normalize(r){const x={...r},raw=[x.yarn_type,x.blend,x.yarn_name,x.product].filter(Boolean).join(' ').toUpperCase();x.product=x.product||'Yarn';if(!x.yarn_type||x.yarn_type==='Cotton Yarn'){if(/COMBED|\bCBD\b/.test(raw))x.yarn_type='Combed Yarn';else if(/CARDED|KARDED|\bKD\b/.test(raw))x.yarn_type='Carded Yarn';else if(/HOSIERY/.test(raw))x.yarn_type='Hosiery Yarn';else x.yarn_type=x.product}x.year=x.year??Number(String(x.date||'').slice(0,4));x.month=x.month??Number(String(x.date||'').slice(5,7));return x}
function selected(id){return $(id)?.value||''}
function rowsExcept(skip){return state.records.filter(r=>filters.every(([id,,,key])=>id===skip||!selected(id)||String(r[key]).toLowerCase()===selected(id).toLowerCase()))}
function filtered(){return state.records.filter(r=>filters.every(([id,,,key])=>!selected(id)||String(r[key]).toLowerCase()===selected(id).toLowerCase())).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function buildFilters(){const box=$('filters');box.innerHTML=filters.map(([id,label,all])=>`<div class="filter"><label>${label}</label><select id="${id}"><option value="">${all}</option></select></div>`).join('');filters.forEach(([id])=>$(id).addEventListener('change',async()=>{populateFilters();renderHistory();renderMarket();await runForecast()}))}
function populateFilters(){filters.forEach(([id,,all,key])=>{const e=$(id),old=e.value;if(!e)return;const vals=unique(rowsExcept(id).map(r=>r[key]));e.innerHTML=`<option value="">${all}</option>`+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(vals.some(v=>String(v).toLowerCase()===String(old).toLowerCase()))e.value=old})}
function monthly(rows){const m={};rows.forEach(r=>{const k=String(r.date||'').slice(0,7),v=Number(r.price_inr_kg);if(/^\d{4}-\d{2}$/.test(k)&&Number.isFinite(v))(m[k]??=[]).push(v)});return Object.keys(m).sort().map(month=>({month,value:mean(m[month])}))}
function chart(key,id,type,data,options={}){if(state.charts[key])state.charts[key].destroy();state.charts[key]=new Chart($(id),{type,data,options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},...options}})}
function renderHistory(){const rows=filtered(),s=monthly(rows);$('history-count').textContent=`${rows.length.toLocaleString()} records`;$('filter-status').textContent=`${rows.length.toLocaleString()} verified observations • ${s.length} monthly points`;chart('history','history-chart','line',{labels:s.map(x=>x.month),datasets:[{label:'Official monthly average ₹/kg',data:s.map(x=>x.value),tension:.25,pointRadius:2,borderWidth:2,fill:true}]},{scales:{y:{beginAtZero:false,title:{display:true,text:'₹ / kg'}}}});renderTable(rows)}
function renderTable(rows){const page=window.TIP_PAGE||1,size=10,total=Math.max(1,Math.ceil(rows.length/size)),p=Math.min(page,total),slice=rows.slice().reverse().slice((p-1)*size,p*size);window.TIP_PAGE=p;$('history-body').innerHTML=slice.length?slice.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.state||'—')}</td><td>${esc(r.district||'—')}</td><td>${esc(r.centre||'—')}</td><td>${esc(r.fiber||'—')}</td><td>${esc(r.product||'—')}</td><td>${esc(r.yarn_type||'—')}</td><td>${esc(r.count||'—')}</td><td>${esc(r.blend||'—')}</td><td>${money(r.price_inr_kg)}</td><td>${esc(r.source_short||r.source||'—')}</td></tr>`).join(''):'<tr><td colspan="11" class="empty">No verified observations match the selected filters.</td></tr>';$('history-pagination').innerHTML=rows.length?`<span>Showing ${(p-1)*size+1}–${Math.min(p*size,rows.length)} of ${rows.length.toLocaleString()}</span><div class="toolbar"><button class="btn" id="prev-page" ${p===1?'disabled':''}>‹ Previous</button><span class="pill indigo">Page ${p} / ${total}</span><button class="btn" id="next-page" ${p===total?'disabled':''}>Next ›</button></div>`:'';if($('prev-page'))$('prev-page').onclick=()=>{window.TIP_PAGE=p-1;renderTable(filtered())};if($('next-page'))$('next-page').onclick=()=>{window.TIP_PAGE=p+1;renderTable(filtered())}}
function renderMarket(){const e=$('market-filter'),old=e.value,markets=unique(state.market.map(r=>r.market));e.innerHTML='<option value="">All Markets</option>'+markets.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(markets.includes(old))e.value=old;let rows=state.market.filter(r=>!selected('fiber')||String(r.fiber).toLowerCase()===selected('fiber').toLowerCase()).filter(r=>!selected('product')||String(r.product).toLowerCase()===selected('product').toLowerCase()).filter(r=>!selected('yarn_type')||String(r.yarn_type).toLowerCase()===selected('yarn_type').toLowerCase()).filter(r=>!selected('count')||String(r.count).toLowerCase()===selected('count').toLowerCase()).filter(r=>!e.value||String(r.market).toLowerCase()===e.value.toLowerCase());const latest=[...new Set(rows.map(r=>r.date).filter(Boolean))].sort().at(-1);rows=latest?rows.filter(r=>r.date===latest):[];const mids=rows.map(r=>(Number(r.price_min_inr_kg)+Number(r.price_max_inr_kg))/2).filter(Number.isFinite);$('market-summary').innerHTML=rows.length?`<div class="market-price">${money(mean(mids))}<small>Market midpoint • ${esc(latest)}</small></div>`:'<div class="empty">No matching published market indication.</div>';$('live-market-body').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.market)}</td><td>${esc(r.product)}</td><td>${esc(r.yarn_type)}</td><td>${esc(r.count)}</td><td>${money(r.price_min_inr_kg)} – ${money(r.price_max_inr_kg)}</td><td><a class="source-link" href="${esc(r.source_url)}" target="_blank" rel="noopener">${esc(r.source)}</a></td></tr>`).join(''):'<tr><td colspan="7" class="empty">No matching market report.</td></tr>'}
function requiredForecastRows(){return filtered().filter(r=>r.date&&Number.isFinite(Number(r.price_inr_kg))&&Number(r.price_inr_kg)>0)}
async function runForecast(){const required=['fiber','product','yarn_type','count'],missing=required.filter(id=>!selected(id)),labels={fiber:'Fiber',product:'Yarn Category',yarn_type:'Yarn Type',count:'Count'};if(missing.length){clearForecast();$('forecast-meta').innerHTML=`<span class="status warn">Select ${missing.map(x=>labels[x]).join(' + ')}</span>`;return}const rows=requiredForecastRows(),h=window.TIP_H||3;if(rows.length<12){clearForecast();$('forecast-meta').innerHTML=`<span class="status warn">Not enough history for this selection (${rows.length} records).</span>`;return}$('system-status').textContent='● Forecasting';$('system-status').className='pill amber';try{const res=await fetch('/api/forecast',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:rows,horizon:h})});let data=null;try{data=await res.json()}catch{throw Error('Forecast service returned invalid JSON.')}if(!res.ok)throw Error(data?.error||`Forecast request failed (${res.status}).`);if(!data.ok)throw Error(data.error||'Forecast could not be generated.');drawForecast(data);$('system-status').textContent='● Ready';$('system-status').className='pill green'}catch(e){clearForecast();$('forecast-meta').innerHTML=`<span class="status warn">Forecast unavailable: ${esc(e.message)}</span>`;console.error(e);$('system-status').textContent='● Forecast error';$('system-status').className='pill amber'}}
function clearForecast(){if(state.charts.forecast){state.charts.forecast.destroy();delete state.charts.forecast}['best-model','backtest-mape','backtest-rmse','history-used'].forEach(id=>{if($(id))$(id).textContent='—'});$('model-body').innerHTML=''}
function drawForecast(d){const labels=[...d.history.map(x=>x.month),...d.forecast.map(x=>x.month)],hist=[...d.history.map(x=>x.price),...Array(d.forecast.length).fill(null)],pred=[...Array(Math.max(0,d.history.length-1)).fill(null),d.history.at(-1).price,...d.forecast.map(x=>x.price)];chart('forecast','forecast-chart','line',{labels,datasets:[{label:'Historical ₹/kg',data:hist,borderWidth:2,pointRadius:2,tension:.25},{label:'Forecast ₹/kg',data:pred,borderWidth:2,borderDash:[7,4],pointRadius:3,tension:.25}]},{scales:{y:{beginAtZero:false,title:{display:true,text:'₹ / kg'}}}});$('forecast-meta').innerHTML=`<span class="status ok">${esc(d.model)} • Rolling backtest: ${d.validation.mape.toFixed(2)}% MAPE • ₹${d.validation.rmse.toFixed(2)} RMSE</span>`;$('best-model').textContent=d.model;$('best-model-metrics').textContent=`${d.validation.n} out-of-sample validation points`;$('backtest-mape').textContent=`${d.validation.mape.toFixed(2)}%`;$('backtest-rmse').textContent=`₹${d.validation.rmse.toFixed(2)}`;$('history-used').textContent=d.monthly_points;$('model-body').innerHTML=d.leaderboard.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.model)}</td><td>${x.mape.toFixed(2)}%</td><td>₹${x.rmse.toFixed(2)}</td><td>${x.n}</td></tr>`).join('');$('forecast-note').textContent=`The engine selected ${d.model} because it had the lowest rolling-origin MAPE, with RMSE used as the tie-breaker. Forecast accuracy is measured from historical holdouts; it is not guaranteed for future market shocks.`}
function render(){window.TIP_PAGE=1;renderHistory();renderMarket();runForecast()}
async function load(){try{const [a,b]=await Promise.all([fetch('/api/yarn',{cache:'no-store'}),fetch('/api/live-yarn',{cache:'no-store'})]);if(!a.ok)throw Error('Yarn data API failed');const y=await a.json(),m=b.ok?await b.json():{records:[]};state.records=(y.records||[]).filter(r=>r.date&&r.date>='2021-01-01').map(normalize);state.market=m.records||[];populateFilters();render();$('system-status').textContent=`● ${state.records.length.toLocaleString()} records`;$('system-status').className='pill green'}catch(e){$('system-status').textContent='● Data error';$('system-status').className='pill amber';console.error(e)}}
function boot(){window.TIP=state;buildFilters();$('refresh-all').onclick=load;$('clear-filters').onclick=async()=>{filters.forEach(([id])=>$(id).value='');populateFilters();render()};$('market-filter').onchange=()=>{renderMarket()};document.querySelectorAll('.forecast-option').forEach(b=>b.onclick=()=>{window.TIP_H=Number(b.dataset.h);runForecast()});load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
