import express from 'express';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
const app=express();const __filename=fileURLToPath(import.meta.url),__dirname=dirname(__filename),PORT=process.env.PORT||10000;
app.disable('x-powered-by');app.use(express.json({limit:'12mb'}));app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');next()});app.use(express.static(__dirname,{extensions:['html']}));
const readJson=f=>JSON.parse(readFileSync(join(__dirname,'data',f),'utf8'));const cache=(res,s=300)=>res.setHeader('Cache-Control',`public,max-age=${s},stale-while-revalidate=1800`);
app.get('/api/yarn',(req,res)=>{try{const d=readJson('yarn.json'),r=d.records||[];cache(res);res.json({records:r,count:r.length,coverage:d.coverage||{},source:d.source||'official-textile-sources'})}catch(e){res.status(500).json({error:'Official yarn dataset could not be loaded'})}});
app.get('/api/live-yarn',(req,res)=>{try{const d=readJson('live_yarn.json'),r=d.records||[],dates=r.map(x=>x.date).filter(Boolean).sort(),latest=dates.at(-1);cache(res,300);res.json({records:r,count:r.length,latest_source_record:latest,latest_count:latest?r.filter(x=>x.date===latest).length:0,source_tier:'MARKET_INDICATOR'})}catch(e){res.status(500).json({error:'Market dataset could not be loaded'})}});
app.get('/api/operations',(req,res)=>{try{const d=readJson('operations.json'),r=d.records||[];res.json({records:r,count:r.length,connected:r.length>0})}catch(e){res.status(500).json({error:'Operations dataset could not be loaded'})}});
app.post('/api/forecast',(req,res)=>{const py=spawn(process.env.PYTHON_BIN||'python3',[join(__dirname,'forecast.py')],{stdio:['pipe','pipe','pipe']});let out='',err='';py.stdout.on('data',x=>out+=x);py.stderr.on('data',x=>err+=x);py.on('close',code=>{if(code!==0){console.error(err);return res.status(500).json({ok:false,error:'Forecast engine failed to execute.'})}try{res.json(JSON.parse(out))}catch(e){res.status(500).json({ok:false,error:'Forecast engine returned invalid output.'})}});py.stdin.end(JSON.stringify(req.body||{}));});
app.get('/health',(req,res)=>res.json({status:'ok',service:'textile-intelligence-platform',forecast_engine:'python'}));
app.listen(PORT,'0.0.0.0',()=>console.log(`Textile Intelligence Platform running on ${PORT}`));
