// api/yarn.js
// Official textile/yarn/fibre price scraper.
// TXC: monthly cotton-yarn history + official weekly price sheets.
// NTC: official Western/Southern yarn price-list archive for the post-Mar-2025 gap.
const HISTORICAL_URL='https://www.txcindia.gov.in/html/ecomicsection/Cotton%20Yarn%20Prices.pdf';
const WEEKLY_URLS=[
 {url:'https://txcindia.gov.in/html/pricessheet3.pdf',sheet:'Cotton Yarn'},
 {url:'https://txcindia.gov.in/html/pricessheet4.pdf',sheet:'Man Made Fibres'},
 {url:'https://txcindia.gov.in/html/pricessheet5.pdf',sheet:'Blended Yarn & Viscose Spun Yarn'},
 {url:'https://txcindia.gov.in/html/pricessheet6.pdf',sheet:'Man Made Filament Yarns'},
 {url:'https://txcindia.gov.in/html/pricessheet7.pdf',sheet:'Wool/Woollen Yarn'}
];
const NTC_ARCHIVES=[
 {url:'https://www.ntcltd.org/WRO_oldRecords.aspx',region:'Western Region'},
 {url:'https://www.ntcltd.org/SRO_oldRecords.aspx',region:'Southern Region'}
];
const NTC_FROM='2025-04-01';
const CENTRE_META={Coimbatore:{state:'Tamil Nadu',district:'Coimbatore'},Amritsar:{state:'Punjab',district:'Amritsar'},Ahmedabad:{state:'Gujarat',district:'Ahmedabad'}};
const MONTHS={Jan:0,January:0,Feb:1,February:1,Mar:2,March:2,Apr:3,April:3,May:4,Jun:5,June:5,Jul:6,July:6,Aug:7,August:7,Sep:8,September:8,Oct:9,October:9,Nov:10,November:10,Dec:11,December:11};
function cleanLine(x){return String(x).replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim()}
function numberOrNull(x){if(x===undefined||x===null||x===''||x==='-'||/^N\.?A\.?$/i.test(String(x)))return null;const n=Number(String(x).replace(/,/g,''));return Number.isFinite(n)?n:null}
function parseMonthToken(t){const m=String(t).match(/^(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)-(\d{2})$/i);if(!m)return null;const k=Object.keys(MONTHS).find(x=>x.toLowerCase()===m[1].toLowerCase());return new Date(Date.UTC(2000+Number(m[2]),MONTHS[k],1))}
function parseDateDMY(x){const m=String(x).match(/(\d{1,2})[./-](\d{1,2})[./-](\d{4})/);if(!m)return null;const d=Number(m[1]),mo=Number(m[2]),y=Number(m[3]);const dt=new Date(Date.UTC(y,mo-1,d));return Number.isNaN(dt.getTime())?null:dt}
function isoDate(dt){return dt.toISOString().slice(0,10)}
function parseHistoricalText(text){const lines=text.split(/\r?\n/).map(cleanLine).filter(Boolean),out=[];let section=null,centre=null;for(const line of lines){if(/Annexure-I/i.test(line))section='Cone Combed';if(/Annexure-II/i.test(line))section='Hosiery Combed';const cm=line.match(/Centre-?\s*wise details:\s*([A-Za-z ]+)/i);if(cm){const c=cm[1].trim();centre=Object.keys(CENTRE_META).find(x=>c.toLowerCase().startsWith(x.toLowerCase()))||null;continue}const t=line.split(' '),date=t.length?parseMonthToken(t[0]):null;if(!date||!centre||!section)continue;const counts=section==='Cone Combed'?(centre==='Amritsar'?['20s','30s','40s']:['20s','30s','40s','60s','80s']):['20s','30s','40s'];const v=t.slice(1);let c=0;for(const count of counts){const p=numberOrNull(v[c]);if(p!==null)out.push({date:isoDate(date),year:date.getUTCFullYear(),month:date.getUTCMonth()+1,state:CENTRE_META[centre].state,district:CENTRE_META[centre].district,centre,fiber:'Cotton',count,blend:section,product:'Cotton Yarn',price_inr_kg:p,frequency:'Monthly',source:'Office of the Textile Commissioner',source_short:'TXC',source_url:HISTORICAL_URL});c+=v[c]==='-'?1:3}}return out}
const PATTERNS=[
 [/POLY\s*\/\s*COTTON\s+BLENDED\s+YARN/i,'Polyester/Cotton','Polyester/Cotton Blended Yarn'],
 [/POLY\s*\/\s*VISC(?:OSE)?\.?\s+BLENDED\s+YARN/i,'Polyester/Viscose','Polyester/Viscose Blended Yarn'],
 [/POLYESTER\s+VISCOSE\s+BLENDED\s+YARN/i,'Polyester/Viscose','Polyester/Viscose Blended Yarn'],
 [/POLYESTER\s+COTTON\s+BLENDED\s+YARN/i,'Polyester/Cotton','Polyester/Cotton Blended Yarn'],
 [/VISCOSE\s+SPUN\s+YARN/i,'Viscose','Viscose Spun Yarn'],
 [/VISCOSE\s+STAPLE\s+FIB(?:R)?E/i,'Viscose','Viscose Staple Fibre'],
 [/POLYESTER\s+STAPLE\s+FIB(?:R)?E/i,'Polyester','Polyester Staple Fibre'],
 [/VISCOSE\s+FILAMENT\s+YARN/i,'Viscose','Viscose Filament Yarn'],
 [/POLYESTER\s+FILAMENT\s+YARN/i,'Polyester','Polyester Filament Yarn'],
 [/NYLON\s+FILAMENT\s+YARN/i,'Nylon','Nylon Filament Yarn'],
 [/ACRYLIC\s+(?:SPUN\s+)?YARN/i,'Acrylic','Acrylic Yarn'],
 [/TEXTURI[ZS]ED\s+YARN/i,'Polyester','Texturised Yarn'],
 [/POLYESTER\s+YARN/i,'Polyester','Polyester Yarn'],
 [/NYLON\s+YARN/i,'Nylon','Nylon Yarn'],
 [/WOOLLEN\s+YARN/i,'Wool','Woollen Yarn'],
 [/WOOL\s+TOPS?/i,'Wool','Wool Tops']
];
function detect(line){for(const [re,f,p] of PATTERNS)if(re.test(line))return{fiber:f,product:p};if(/COTTON\s+YARN|COMBED\s+YARN/i.test(line))return{fiber:'Cotton',product:'Cotton Yarn'};return null}
function parseWeeklyText(text,source){const lines=text.split(/\r?\n/).map(cleanLine).filter(Boolean),out=[];let reportDate=null;for(const line of lines){const dm=line.match(/(?:week\s+ending|for\s+the\s+week\s+ending|as\s+on)\s*[:\-]?\s*(\d{1,2}[./-]\d{1,2}[./-]\d{4})/i);if(dm)reportDate=isoDate(parseDateDMY(dm[1]));const d=detect(line);if(!d)continue;const idx=line.toUpperCase().indexOf(d.product.toUpperCase());const tail=idx>=0?line.slice(idx+d.product.length):line;const nums=tail.match(/\b\d{2,5}(?:\.\d+)?\b/g)||[];const p=nums.map(numberOrNull).find(n=>n!==null&&n>20&&n<100000);if(p===undefined)continue;const dt=reportDate||isoDate(new Date());out.push({date:dt,year:Number(dt.slice(0,4)),month:Number(dt.slice(5,7)),state:'All India',district:'Official weekly report',centre:'Official market average',fiber:d.fiber,count:'Average',blend:/BLENDED/i.test(d.product)?d.product:'—',product:d.product,price_inr_kg:p,frequency:'Weekly',source:'Office of the Textile Commissioner',source_short:'TXC',source_url:source.url})}return out}
function extractNTCItems(html,archiveUrl,region){const rows=html.match(/<tr[\s\S]*?<\/tr>/gi)||[],out=[];for(const row of rows){const text=cleanLine(row.replace(/<[^>]+>/g,' '));if(!/YARN\s+(?:H1\s+)?PRICE\s+LIST/i.test(text))continue;const dm=text.match(/(\d{1,2}[./-]\d{1,2}[./-]\d{4})/);if(!dm)continue;const dt=parseDateDMY(dm[1]);if(!dt||isoDate(dt)<NTC_FROM)continue;const hrefs=[];const re=/(?:href|data-href)\s*=\s*["']([^"']+)["']/gi;let m;while((m=re.exec(row)))hrefs.push(m[1]);const onclick=row.match(/(?:window\.open|location(?:\.href)?|open)\s*\([^)]*["']([^"']+)["']/i);if(onclick)hrefs.push(onclick[1]);let href=hrefs.find(x=>/\.pdf(?:[?#]|$)/i.test(x))||hrefs.find(x=>/^https?:/i.test(x));if(!href)continue;try{href=new URL(href,archiveUrl).href}catch{continue}out.push({region,date:isoDate(dt),title:text.replace(/\s+/g,' '),url:href})}return out}
function classifyNTC(variety,section){const s=`${section||''} ${variety||''}`.toUpperCase();if(/POLYESTER.*VISCOSE|\bPV\b|VISCOSE.*POLYESTER/.test(s))return{fiber:'Polyester/Viscose',product:'Polyester/Viscose Blended Yarn'};if(/POLYESTER.*COTTON|\bPC\b|COTTON.*POLYESTER/.test(s))return{fiber:'Polyester/Cotton',product:'Polyester/Cotton Blended Yarn'};if(/VISCOSE|\bVSF\b/.test(s))return{fiber:'Viscose',product:'Viscose Yarn'};if(/POLYESTER|\bPSF\b/.test(s))return{fiber:'Polyester',product:'Polyester Yarn'};if(/NYLON/.test(s))return{fiber:'Nylon',product:'Nylon Yarn'};if(/ACRYLIC/.test(s))return{fiber:'Acrylic',product:'Acrylic Yarn'};if(/WOOL|WOOLLEN/.test(s))return{fiber:'Wool',product:'Wool Yarn'};if(/LINEN/.test(s))return{fiber:'Linen',product:'Linen Yarn'};if(/HEMP/.test(s))return{fiber:'Hemp',product:'Hemp Yarn'};if(/SILK/.test(s))return{fiber:'Silk',product:'Silk Yarn'};if(/MODAL/.test(s))return{fiber:'Modal',product:'Modal Yarn'};if(/LYOCELL/.test(s))return{fiber:'Lyocell',product:'Lyocell Yarn'};if(/COTTON|COMBED|CBD|\bKD\b|\bK\b/.test(s))return{fiber:'Cotton',product:'Cotton Yarn'};return null}
function extractCount(variety){const s=String(variety||'').toUpperCase();const m=s.match(/(?:^|[ /-])(\d{1,3})(?:S|SK|CC|KD|C|S?)(?:\b|$)/);return m?m[1]+'s':(s.match(/\b\d{1,3}S\b/)||[])[0]||'—'}
function parseNTCText(text,item){const lines=text.split(/\r?\n/).map(cleanLine).filter(Boolean),out=[];let section='';for(const line of lines){if(/COTTON YARN/i.test(line)&&!(/POLY/i.test(line)))section='COTTON YARN';else if(/POLYESTER YARN/i.test(line))section='POLYESTER YARN';else if(/VISCOSE/i.test(line)&&/YARN/i.test(line))section='VISCOSE YARN';else if(/NYLON/i.test(line)&&/YARN/i.test(line))section='NYLON YARN';else if(/ACRYLIC/i.test(line)&&/YARN/i.test(line))section='ACRYLIC YARN';else if(/WOOL/i.test(line)&&/YARN/i.test(line))section='WOOL YARN';const rateMatch=line.match(/(?:^|\s)(\d+(?:\.\d{1,2})?)\s+Ex[- ]?Mill\s+Rate\s*\/\s*kg\b/i)||line.match(/(?:^|\s)(\d+(?:\.\d{1,2})?)\s+(?:Ex[- ]?Mill|RateType)/i);if(!rateMatch)continue;const rate=numberOrNull(rateMatch[1]);if(rate===null||rate<=0||rate>=10000)continue;const before=line.slice(0,rateMatch.index).trim();const parts=before.split(/\s{2,}/).map(cleanLine).filter(Boolean);let variety=before;let mill='';if(parts.length>=2){variety=parts[0];mill=parts.slice(1).join(' ')}else{const mm=before.match(/^(.*?)\s+([A-Z][A-Za-z0-9&().,' -]{2,})$/);if(mm){variety=mm[1];mill=mm[2]}}const c=classifyNTC(variety,section);if(!c)continue;const dt=parseDateDMY(item.date);out.push({date:item.date,year:dt.getUTCFullYear(),month:dt.getUTCMonth()+1,state:'Not specified by source',district:item.region,centre:item.region,fiber:c.fiber,count:extractCount(variety),blend:/BLENDED|\bPC\b|\bPV\b|52:48|67:33|70:30/i.test(variety)?variety.match(/\b(?:PC|PV)\b|\d{2}:\d{2}/i)?.[0]||'Blended':'—',product:c.product,yarn_name:variety,mill_name:mill||'NTC',price_inr_kg:rate,frequency:'Weekly/Meeting',source:'National Textile Corporation',source_short:'NTC',source_url:item.url,region:item.region})}return out}
async function fetchPdf(url){const r=await fetch(url,{headers:{'User-Agent':'Textile-Intelligence-Platform/5.0','Accept':'application/pdf,*/*'},redirect:'follow'});if(!r.ok)throw new Error(`HTTP ${r.status}: ${url}`);return Buffer.from(await r.arrayBuffer())}
async function parsePdf(b){const pdfParse=(await import('pdf-parse')).default;return (await pdfParse(b)).text||''}
async function fetchHistorical(){return parseHistoricalText(await parsePdf(await fetchPdf(HISTORICAL_URL)))}
async function fetchWeekly(source){try{return parseWeeklyText(await parsePdf(await fetchPdf(source.url)),source)}catch(e){console.warn(`Official ${source.sheet} unavailable:`,e.message);return[]}}
async function fetchNTCArchive(archive){try{const r=await fetch(archive.url,{headers:{'User-Agent':'Textile-Intelligence-Platform/5.0','Accept':'text/html,*/*'},redirect:'follow'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text();const items=extractNTCItems(html,archive.url,archive.region);const settled=await Promise.allSettled(items.map(async item=>parseNTCText(await parsePdf(await fetchPdf(item.url)),item)));return settled.flatMap(x=>x.status==='fulfilled'?x.value:[])}catch(e){console.warn(`NTC ${archive.region} unavailable:`,e.message);return[]}}
function dedupe(a){const s=new Set();return a.filter(r=>{const k=[r.date,r.source_short,r.region||'',r.centre,r.fiber,r.count,r.yarn_name||r.product,r.price_inr_kg].join('|');if(s.has(k))return false;s.add(k);return true})}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=86400');res.setHeader('Access-Control-Allow-Origin','*');try{const [h,...rest]=await Promise.all([fetchHistorical(),...WEEKLY_URLS.map(fetchWeekly),...NTC_ARCHIVES.map(fetchNTCArchive)]);const records=dedupe([...h,...rest.flat()]).sort((a,b)=>a.date.localeCompare(b.date)||a.fiber.localeCompare(b.fiber)||String(a.count).localeCompare(String(b.count),undefined,{numeric:true}));const dates=records.map(r=>r.date).sort();const ntcCount=records.filter(r=>r.source_short==='NTC').length;return res.status(200).json({source:'official-textile-sources',records,count:records.length,fiber_types:[...new Set(records.map(r=>r.fiber).filter(Boolean))].sort(),product_types:[...new Set(records.map(r=>r.product).filter(Boolean))].sort(),coverage:{historical_cotton:'January 2021 to March 2025',ntc_post_mar_2025_records:ntcCount,latest_source_record:dates.at(-1)||null,weekly_sheets_attempted:WEEKLY_URLS.map(x=>x.sheet),ntc_archives_attempted:NTC_ARCHIVES.map(x=>x.region),note:'Filters and categories are derived from successfully parsed official source rows. No unsupported fiber/category is hardcoded.'},fetched_at:new Date().toISOString()})}catch(e){console.error(e);return res.status(502).json({error:'Could not scrape official textile price sources.',detail:e instanceof Error?e.message:String(e)})}}
