// Official yarn/fibre price ingestion for Textile Intelligence Platform.
// Sources: Office of the Textile Commissioner (TXC) + National Textile Corporation (NTC).
const MIN_DATE='2021-01-01';
const NTC_FROM='2025-04-01';
const HISTORICAL_URL='https://www.txcindia.gov.in/html/ecomicsection/Cotton%20Yarn%20Prices.pdf';
const WEEKLY_URLS=[
 {url:'https://txcindia.gov.in/html/pricessheet3.pdf',sheet:'Cotton Yarn'},
 {url:'https://txcindia.gov.in/html/pricessheet4.pdf',sheet:'Man Made Fibres'},
 {url:'https://txcindia.gov.in/html/pricessheet5.pdf',sheet:'Blended Yarn & Viscose Spun Yarn'},
 {url:'https://txcindia.gov.in/html/pricessheet6.pdf',sheet:'Man Made Filament Yarns'},
 {url:'https://txcindia.gov.in/html/pricessheet7.pdf',sheet:'Wool/Woollen Yarn'}
];
const NTC_ARCHIVES=[
 {url:'https://www.ntcltd.org/WRO_oldRecords.aspx',region:'Western Region'},
 {url:'https://www.ntcltd.org/SRO_oldRecords.aspx',region:'Southern Region'}
];
const CENTRES={Coimbatore:{state:'Tamil Nadu',district:'Coimbatore'},Amritsar:{state:'Punjab',district:'Amritsar'},Ahmedabad:{state:'Gujarat',district:'Ahmedabad'}};
const MONTHS={Jan:0,January:0,Feb:1,February:1,Mar:2,March:2,Apr:3,April:3,May:4,Jun:5,June:5,Jul:6,July:6,Aug:7,August:7,Sep:8,September:8,Oct:9,October:9,Nov:10,November:10,Dec:11,December:11};
const clean=s=>String(s??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const num=s=>{if(s==null||s===''||s==='-'||/^N\.?A\.?$/i.test(String(s)))return null;const n=Number(String(s).replace(/,/g,''));return Number.isFinite(n)?n:null};
function dmy(s){const m=String(s).match(/(\d{1,2})[./-](\d{1,2})[./-](\d{4})/);if(!m)return null;const d=new Date(Date.UTC(+m[3],+m[2]-1,+m[1]));return Number.isNaN(d.getTime())?null:d}
function iso(d){return d.toISOString().slice(0,10)}
function monthToken(s){const m=String(s).match(/^(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)-(\d{2})$/i);if(!m)return null;const k=Object.keys(MONTHS).find(x=>x.toLowerCase()===m[1].toLowerCase());return new Date(Date.UTC(2000+ +m[2],MONTHS[k],1))}
async function pdfText(url){const r=await fetch(url,{headers:{'User-Agent':'Textile-Intelligence-Platform/6.0','Accept':'application/pdf,*/*'},redirect:'follow',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=Buffer.from(await r.arrayBuffer());const pdfParse=(await import('pdf-parse')).default;return (await pdfParse(b)).text||''}
function historical(text){const lines=text.split(/\r?\n/).map(clean).filter(Boolean),out=[];let section='',centre='';for(const line of lines){if(/Annexure-I/i.test(line))section='Cone Combed';if(/Annexure-II/i.test(line))section='Hosiery Combed';const cm=line.match(/Centre-?\s*wise details:\s*([A-Za-z ]+)/i);if(cm){const n=cm[1].trim();centre=Object.keys(CENTRES).find(k=>n.toLowerCase().startsWith(k.toLowerCase()))||'';continue}const dt=monthToken(line.split(' ')[0]);if(!dt||!centre||!section||iso(dt)<MIN_DATE)continue;const counts=section==='Cone Combed'&&centre==='Amritsar'?['20s','30s','40s']:section==='Cone Combed'?['20s','30s','40s','60s','80s']:['20s','30s','40s'];const vals=line.split(' ').slice(1);let pos=0;for(const count of counts){const p=num(vals[pos]);if(p!==null)out.push({date:iso(dt),year:dt.getUTCFullYear(),month:dt.getUTCMonth()+1,state:CENTRES[centre].state,district:CENTRES[centre].district,centre,fiber:'Cotton',count,blend:section,product:'Cotton Yarn',price_inr_kg:p,frequency:'Monthly',source:'Office of the Textile Commissioner',source_short:'TXC',source_url:HISTORICAL_URL});pos+=vals[pos]==='-'?1:3}}return out}
const PATTERNS=[[/POLY\s*\/\s*COTTON\s+BLENDED\s+YARN/i,'Polyester/Cotton','Polyester/Cotton Blended Yarn'],[/POLY\s*\/\s*VISC(?:OSE)?\.?\s+BLENDED\s+YARN/i,'Polyester/Viscose','Polyester/Viscose Blended Yarn'],[/POLYESTER\s+VISCOSE\s+BLENDED\s+YARN/i,'Polyester/Viscose','Polyester/Viscose Blended Yarn'],[/POLYESTER\s+COTTON\s+BLENDED\s+YARN/i,'Polyester/Cotton','Polyester/Cotton Blended Yarn'],[/VISCOSE\s+SPUN\s+YARN/i,'Viscose','Viscose Spun Yarn'],[/VISCOSE\s+STAPLE\s+FIB(?:R)?E/i,'Viscose','Viscose Staple Fibre'],[/POLYESTER\s+STAPLE\s+FIB(?:R)?E/i,'Polyester','Polyester Staple Fibre'],[/VISCOSE\s+FILAMENT\s+YARN/i,'Viscose','Viscose Filament Yarn'],[/POLYESTER\s+FILAMENT\s+YARN/i,'Polyester','Polyester Filament Yarn'],[/NYLON\s+FILAMENT\s+YARN/i,'Nylon','Nylon Filament Yarn'],[/ACRYLIC\s+(?:SPUN\s+)?YARN/i,'Acrylic','Acrylic Yarn'],[/TEXTURI[ZS]ED\s+YARN/i,'Polyester','Texturised Yarn'],[/POLYESTER\s+YARN/i,'Polyester','Polyester Yarn'],[/NYLON\s+YARN/i,'Nylon','Nylon Yarn'],[/WOOLLEN\s+YARN/i,'Wool','Woollen Yarn'],[/WOOL\s+TOPS?/i,'Wool','Wool Tops']];
function classify(line){for(const [re,f,p] of PATTERNS)if(re.test(line))return{fiber:f,product:p};if(/COTTON\s+YARN|COMBED\s+YARN/i.test(line))return{fiber:'Cotton',product:'Cotton Yarn'};return null}
function weekly(text,source){const lines=text.split(/\r?\n/).map(clean).filter(Boolean),out=[];let reportDate='';for(const line of lines){const m=line.match(/(?:week\s+ending|for\s+the\s+week\s+ending|as\s+on|dated|date)\s*[:\-]?\s*(\d{1,2}[./-]\d{1,2}[./-]\d{4})/i);if(m){const dt=dmy(m[1]);if(dt)reportDate=iso(dt)}const c=classify(line);if(!c||!reportDate||reportDate<MIN_DATE)continue;const idx=line.toUpperCase().indexOf(c.product.toUpperCase());const tail=idx>=0?line.slice(idx+c.product.length):line;const candidates=(tail.match(/\b\d{2,5}(?:\.\d+)?\b/g)||[]).map(num).filter(n=>n!==null&&n>20&&n<100000);if(!candidates.length)continue;out.push({date:reportDate,year:+reportDate.slice(0,4),month:+reportDate.slice(5,7),state:'All India',district:'Official weekly report',centre:'Official market average',fiber:c.fiber,count:'Average',blend:/BLENDED/i.test(c.product)?c.product:'—',product:c.product,price_inr_kg:candidates[0],frequency:'Weekly',source:'Office of the Textile Commissioner',source_short:'TXC',source_url:source.url})}return out}
function archiveItems(html,archive){const rows=html.match(/<tr[\s\S]*?<\/tr>/gi)||[],out=[];for(const row of rows){const text=clean(row.replace(/<[^>]+>/g,' '));if(!/YARN\s+(?:H1\s+)?PRICE\s+LIST/i.test(text))continue;const m=text.match(/(\d{1,2}[./-]\d{1,2}[./-]\d{4})/);const dt=m&&dmy(m[1]);if(!dt||iso(dt)<NTC_FROM)continue;const urls=[];const re=/(?:href|data-href|src)\s*=\s*["']([^"']+)["']/gi;let x;while((x=re.exec(row)))urls.push(x[1]);const quoted=row.match(/["']([^"']+(?:\.pdf|YPL|Yarn)[^"']*)["']/i);if(quoted)urls.push(quoted[1]);const href=urls.map(u=>{try{return new URL(u,archive.url).href}catch{return ''}}).find(u=>/\.pdf(?:[?#]|$)/i.test(u)||/Writereaddata.*(?:YPL|Yarn)/i.test(u));if(href)out.push({region:archive.region,date:iso(dt),url:href,title:text})}return out}
function ntcClass(s){const t=String(s).toUpperCase();if(/POLYESTER.*VISCOSE|VISCOSE.*POLYESTER|\bPV\b/.test(t))return['Polyester/Viscose','Polyester/Viscose Blended Yarn'];if(/POLYESTER.*COTTON|COTTON.*POLYESTER|\bPC\b/.test(t))return['Polyester/Cotton','Polyester/Cotton Blended Yarn'];if(/VISCOSE|VSF/.test(t))return['Viscose','Viscose Yarn'];if(/POLYESTER|PSF/.test(t))return['Polyester','Polyester Yarn'];if(/NYLON/.test(t))return['Nylon','Nylon Yarn'];if(/ACRYLIC/.test(t))return['Acrylic','Acrylic Yarn'];if(/WOOL|WOOLLEN/.test(t))return['Wool','Wool Yarn'];if(/LINEN/.test(t))return['Linen','Linen Yarn'];if(/HEMP/.test(t))return['Hemp','Hemp Yarn'];if(/SILK/.test(t))return['Silk','Silk Yarn'];if(/MODAL/.test(t))return['Modal','Modal Yarn'];if(/LYOCELL/.test(t))return['Lyocell','Lyocell Yarn'];if(/COTTON|COMBED/.test(t))return['Cotton','Cotton Yarn'];return null}
function countFrom(s){const m=String(s).match(/(?:^|[ /-])(\d{1,3})\s*S\b/i);return m?m[1]+'s':'—'}
function parseNtc(text,item){const lines=text.split(/\r?\n/).map(clean).filter(Boolean),out=[];let section='';for(let i=0;i<lines.length;i++){const line=lines[i];if(/COTTON YARN/i.test(line)&&!/POLY/i.test(line))section='Cotton';else if(/POLYESTER.*YARN/i.test(line))section='Polyester';else if(/VISCOSE.*YARN/i.test(line))section='Viscose';else if(/NYLON.*YARN/i.test(line))section='Nylon';else if(/ACRYLIC.*YARN/i.test(line))section='Acrylic';else if(/WOOL.*YARN/i.test(line))section='Wool';const rate=/\b(\d+(?:\.\d{1,2})?)\s*(?:Ex[- ]?Mill|Rate(?:\s*\/\s*kg)?|Ex[- ]?Mill\s+Rate\s*\/\s*kg)\b/i.exec(line);if(!rate)continue;const price=num(rate[1]);if(price===null||price<=0||price>=10000)continue;const before=line.slice(0,rate.index).trim();const prior=i>0?lines[i-1]:'';const variety=before||prior;const c=ntcClass(`${section} ${variety}`);if(!c)continue;const dt=dmy(item.date);if(!dt||iso(dt)<MIN_DATE)continue;out.push({date:item.date,year:dt.getUTCFullYear(),month:dt.getUTCMonth()+1,state:'Not specified by source',district:item.region,centre:item.region,fiber:c[0],count:countFrom(variety),blend:/BLENDED|\bPC\b|\bPV\b|\d{2}:\d{2}/i.test(variety)?'Blended':'—',product:c[1],yarn_name:variety,mill_name:'NTC',price_inr_kg:price,frequency:'Weekly/Meeting',source:'National Textile Corporation',source_short:'NTC',source_url:item.url,region:item.region})}return out}
async function fetchNtcArchive(archive){try{const r=await fetch(archive.url,{headers:{'User-Agent':'Textile-Intelligence-Platform/6.0','Accept':'text/html,*/*'},redirect:'follow',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text();const items=archiveItems(html,archive);const results=[];const concurrency=6;for(let i=0;i<items.length;i+=concurrency){const batch=items.slice(i,i+concurrency);const settled=await Promise.allSettled(batch.map(async item=>parseNtc(await pdfText(item.url),item)));for(const x of settled)if(x.status==='fulfilled')results.push(...x.value)}return results}catch(e){console.warn(`NTC ${archive.region}:`,e.message);return[]}}
function dedupe(rows){const seen=new Set();return rows.filter(r=>{if(!r.date||r.date<MIN_DATE||!Number.isFinite(Number(r.price_inr_kg)))return false;const k=[r.date,r.source_short,r.region||'',r.centre,r.fiber,r.count,r.yarn_name||r.product,r.price_inr_kg].join('|');if(seen.has(k))return false;seen.add(k);return true})}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=86400');res.setHeader('Access-Control-Allow-Origin','*');try{const [h,...rest]=await Promise.all([pdfText(HISTORICAL_URL).then(historical),...WEEKLY_URLS.map(s=>pdfText(s.url).then(t=>weekly(t,s)).catch(e=>{console.warn(`TXC ${s.sheet}:`,e.message);return[]})),...NTC_ARCHIVES.map(fetchNtcArchive)]);const records=dedupe([h,...rest.flat()]).sort((a,b)=>a.date.localeCompare(b.date)||a.fiber.localeCompare(b.fiber)||String(a.count).localeCompare(String(b.count),undefined,{numeric:true}));const dates=records.map(r=>r.date).sort();const ntc=records.filter(r=>r.source_short==='NTC');return res.status(200).json({source:'official-textile-sources',records,count:records.length,fiber_types:[...new Set(records.map(r=>r.fiber).filter(Boolean))].sort(),product_types:[...new Set(records.map(r=>r.product).filter(Boolean))].sort(),coverage:{minimum_date:MIN_DATE,historical_cotton:'January 2021 to March 2025',ntc_post_mar_2025_records:ntc.length,latest_source_record:dates.at(-1)||null,weekly_sheets_attempted:WEEKLY_URLS.map(x=>x.sheet),ntc_archives_attempted:NTC_ARCHIVES.map(x=>x.region),note:'Only successfully parsed official source rows dated 2021-01-01 or later are returned. Filter categories are derived from those records; no year/fiber values are hardcoded.'},fetched_at:new Date().toISOString()})}catch(e){console.error(e);return res.status(502).json({error:'Could not scrape official textile price sources.',detail:e instanceof Error?e.message:String(e)})}}